services:
  rabbitmq:
    image: "rabbitmq:3.13.2"
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq


volumes:
  rabbitmq_data:
    driver: "local"
